import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../src/layout/Header'
import Footer from '../src/layout/Footer'
import MyCarousel from '../src/component/MyCarousel'
import { AiOutlineArrowLeft } from 'react-icons/ai'
import CardDefault from '../src/component/CardDefulte'
import vipText from '../src/asset/vipText.png'
import Image from 'next/image'
import { Button, Spinner } from 'flowbite-react'
import CardVip from '../src/component/CardVip'
import CardHelp from '../src/component/CardHelp'
import Cardoffer from '../src/component/CardOffer'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { json } from 'stream/consumers'
import { useDispatch, useSelector } from 'react-redux'
import { fetchProducts, fetchCategories } from '../src/redux/slice/productSlice'




const Home: NextPage = () => {
  interface Icategory{
    children: any,
    featured: boolean,
    icon: string,
    id: number,
    image: string,
    name: string,
    parent:any,
    slug: string,
  }

  
  interface Iproduct{
    id: number;
    attributes: string;
    category: number;
    description: string;
    extra_information: string;
    featured: boolean;
    final_price: string;
    images: string[];
    main_image: string;
    name: string;
    options: string[];
    price: string;
    remaining: number;
    slug: string | null;
  }
  
  const dispatch = useDispatch()
    const productList = useSelector((state:any) => state.product.product)
    const categoryList = useSelector((state:any) => state.product.category)
    useEffect(() => {
        dispatch((fetchProducts()))
        dispatch((fetchCategories()))
    }, [])

  // login and get token from server
  // const [token, setToken] = useState('1467bb8db9c5d9d2f4511a869a34a3055f121af4');
  // useEffect(() => {
  //   fetch('http://localhost:8000/user/login', {
  //     method: 'POST',
  //     headers: {
  //       'Content-Type': 'application/json'
  //     },
  //     body: JSON.stringify({
  //       username: 'admin',
  //       password: 'pbkdf2_sha256$260000$DQhKx9N9kLUYefC1qPofcT$ulH8grSv8n8qerA24eYhqlBbiqMB52tX7SB6EBkYHqU='
  //     })
  //   })
  //     .then(response => response.json())
  //     .then(data => {
  //       //setToken(data.token); 
  //       console.log(data,'hi')})
  //     .catch(err => console.error(err));
  // }, []);


  // useEffect(() => {
  //   if (token) {
  //     fetch('http://localhost:8000/store/product', {
  //       method: 'GET',
  //       headers: {
  //         'Content-Type': 'application/json',
  //         'Authorization': `Token ${token}`
  //       }
  //     })
  //       .then(response => response.json())
  //       .then(data => {setData(data); console.log(data)})
  //       .catch(err => console.error(err));
        
  //   }
  // }, [token]);


  return (
    <div>
      <Head>
        <title>T-Cloud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className='bg-mybackground pt-6'>
        <div className='w-full lg:w-2/3 md:w-3/4 sm:w-4/5 mx-auto flex flex-col'>
          <MyCarousel />
          <div className=' translate-y-[-230%] self-center'>
            <Link href='/products'>
            <Button size='lg' color="purple">!بهترین باش</Button>
            </Link>
          </div>
        </div>
        <div className='w-2/3 grid grid-cols-2 mx-auto sm:grid-cols-4 gap-4 mt-8 text-mywhite'>
          {
            categoryList?.map((item:Icategory, index:number) => {
              return (
                <Link href={`/products?category=${item.name}`} key={index}>
                <button className='bg-white hover:scale-95 w-full h-28 flex justify-between items-center text-myprimary-100 text-xl pl-2 md:pl-8 overflow-hidden shadow-none hover:shadow-myprimary-100 hover:shadow-lg' key={index}>
                  <span className='flex items-center'>{item.name}</span>
                  <img src={item.image} className='w-auto h-full object-fill' />
                </button>
                </Link>
              )
            })
          }

        </div>
        {/* scroll-shop-vip */}
        <div className='w-full overflow-x-scroll flex items-center gap-4 mt-20 px-6 no-scrollbar' dir='rtl'>

          <div>

            <Image
              layout='fixed'
              src='/asset/vipText.png'
              alt='vipText'
              height={150}
              width={150}
            />
          </div>

          {
            productList?.map((item:Iproduct, index:number) => {
              if(item.slug === 'vip'){
                return (
                  <div>
                    <CardVip
                      brand={item.description}
                      label={item.name}
                      price={parseFloat(item.price)}
                      size={(item.options.filter((item2:string) => item2 !== 'ALL'))}
                      url={item.main_image}
                      rate={4}
                      />
                  </div>
                )
              }
            })
          }

          
        </div>


        {/* scroll-shop-help */}
        <div className='w-full overflow-x-scroll flex items-center gap-4 mt-12 px-6 no-scrollbar' dir='rtl'>

          <div>

            <Image
              layout='fixed'
              src='/asset/helpText.png'
              alt='vipText'
              height={150}
              width={150}
            />
          </div>
          

          {
            productList?.map((item:Iproduct, index:number) => {
              if(item.slug === 'help'){
                return (
                  <div>
                    <CardHelp
                      brand={item.description}
                      label={item.name}
                      price={parseFloat(item.price)}
                      size={(item.options.filter((item2:string) => item2 !== 'ALL'))}
                      url={item.main_image}
                      rate={4}
                      />
                  </div>
                )
              }
            })
          }

        


        </div>
        {/* scroll-shop-offer */}
        <div className='w-full overflow-x-scroll flex items-center gap-4 mt-12 px-6 no-scrollbar' dir='rtl'>

          <div>
        <Image
              layout='fixed'
              src='/asset/offerText.png'
              alt='vipText'
              height={150}
              width={150}
            />
          </div>

          {
            productList?.map((item:Iproduct, index:number) => {
              if(item.slug === 'off'){
                return (
                  <div>
                    <Cardoffer
                    oldPrice={parseFloat(item.price)}
                      brand={item.description}
                      label={item.name}
                      price={parseFloat(item.final_price)}
                      size={(item.options.filter((item2:string) => item2 !== 'ALL'))}
                      url={item.main_image}
                      rate={4}
                      />
                  </div>
                )
              }
            })
          }
          
            
        </div>
      </main>

      <Footer />
    </div>
  )
}

export default Home
