version: '3.7'
services:
  ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "63342:63342"
    links:
      - postgres:postgres
      - redis:redis
    env_file:
      - ./environments/production.env
#    command:  bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis
      - postgres
    volumes:
      - ./:/usr/src/app


  redis:
    image: redis:6
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ecommerce
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ecommerce
    depends_on:
      - postgres
    env_file:
      - environments/.postgres
    ports:
      - "5050:5050"

volumes:
  redis-data:
  postgres:
  file-data:



